settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: remote-and-chill
  path: .
  commands:
    generate:
      status: true
    install:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    - graphql
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
